In [3]:
import pandas as pd
chexpert = pd.read_csv(r'C:\Users\trodr\Documents\proyecto-torax-v2.0\01-dataset\mimic-cxr-2.0.0-chexpert.csv')
chexpert.columns

Index(['subject_id', 'study_id', 'Atelectasis', 'Cardiomegaly',
       'Consolidation', 'Edema', 'Enlarged Cardiomediastinum', 'Fracture',
       'Lung Lesion', 'Lung Opacity', 'No Finding', 'Pleural Effusion',
       'Pleural Other', 'Pneumonia', 'Pneumothorax', 'Support Devices'],
      dtype='str')

In [3]:
chexpert.head(6)

,subject_id,study_id,Atelectasis,Cardiomegaly,Consolidation,Edema,Enlarged Cardiomediastinum,Fracture,Lung Lesion,Lung Opacity,No Finding,Pleural Effusion,Pleural Other,Pneumonia,Pneumothorax,Support Devices
0,10000032,50414267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,10000032,53189527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2,10000032,53911762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
3,10000032,56699142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
4,10000764,57375967,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN
5,10000898,50771383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN

In [8]:
metadata = pd.read_csv(r'C:\Users\trodr\Documents\proyecto-torax-v2.0\01-dataset\mimic-cxr-2.0.0-metadata.csv')
metadata.columns

Index(['dicom_id', 'subject_id', 'study_id',
       'PerformedProcedureStepDescription', 'ViewPosition', 'Rows', 'Columns',
       'StudyDate', 'StudyTime', 'ProcedureCodeSequence_CodeMeaning',
       'ViewCodeSequence_CodeMeaning',
       'PatientOrientationCodeSequence_CodeMeaning'],
      dtype='str')

In [10]:
union = metadata[['dicom_id', 'subject_id', 'study_id']].copy()
union.columns
union.head(6)

                                       dicom_id  subject_id  study_id
0  02aa804e-bde0afdd-112c0b34-7bc16630-4e384014    10000032  50414267
1  174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962    10000032  50414267
2  2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab    10000032  53189527
3  e084de3b-be89b11e-20fe3f9f-9c8d8dfe-4cfd202c    10000032  53189527
4  68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714    10000032  53911762
5  fffabebf-74fd3a1f-673b6b41-96ec0ac9-2ab69818    10000032  53911762

In [7]:
metadata.head(6)

,dicom_id,subject_id,study_id,PerformedProcedureStepDescription,ViewPosition,Rows,Columns,StudyDate,StudyTime,ProcedureCodeSequence_CodeMeaning,ViewCodeSequence_CodeMeaning,PatientOrientationCodeSequence_CodeMeaning
0,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,10000032,50414267,CHEST (PA AND LAT),PA,3056,2544,21800506,213014.531,CHEST (PA AND LAT),postero-anterior,Erect
1,174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962,10000032,50414267,CHEST (PA AND LAT),LATERAL,3056,2544,21800506,213014.531,CHEST (PA AND LAT),lateral,Erect
2,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,10000032,53189527,CHEST (PA AND LAT),PA,3056,2544,21800626,165500.312,CHEST (PA AND LAT),postero-anterior,Erect
3,e084de3b-be89b11e-20fe3f9f-9c8d8dfe-4cfd202c,10000032,53189527,CHEST (PA AND LAT),LATERAL,3056,2544,21800626,165500.312,CHEST (PA AND LAT),lateral,Erect
4,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,10000032,53911762,CHEST (PORTABLE AP),AP,2705,2539,21800723,80556.875,CHEST (PORTABLE AP),antero-posterior,NaN
5,fffabebf-74fd3a1f-673b6b41-96ec0ac9-2ab69818,10000032,53911762,CHEST (PORTABLE AP),AP,2906,2258,21800723,80556.875,CHEST (PORTABLE AP),antero-posterior,Erect

In [8]:
negbio = pd.read_csv(r'C:\Users\trodr\Documents\proyecto-torax-v2.0\01-dataset\mimic-cxr-2.0.0-negbio.csv')
negbio.columns

Index(['subject_id', 'study_id', 'Atelectasis', 'Cardiomegaly',
       'Consolidation', 'Edema', 'Enlarged Cardiomediastinum', 'Fracture',
       'Lung Lesion', 'Lung Opacity', 'No Finding', 'Pleural Effusion',
       'Pleural Other', 'Pneumonia', 'Pneumothorax', 'Support Devices'],
      dtype='str')

In [9]:
negbio.head(6)

,subject_id,study_id,Atelectasis,Cardiomegaly,Consolidation,Edema,Enlarged Cardiomediastinum,Fracture,Lung Lesion,Lung Opacity,No Finding,Pleural Effusion,Pleural Other,Pneumonia,Pneumothorax,Support Devices
0,10000032,50414267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,10000032,53189527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2,10000032,53911762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
3,10000032,56699142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
4,10000764,57375967,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN
5,10000898,50771383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN

In [10]:
split   = pd.read_csv(r'C:\Users\trodr\Documents\proyecto-torax-v2.0\01-dataset\mimic-cxr-2.0.0-split.csv')
split.columns

Index(['dicom_id', 'study_id', 'subject_id', 'split'], dtype='str')

In [21]:
split.head(6)
split['split'].unique()

<StringArray>
['train', 'validate', 'test']
Length: 3, dtype: str

In [14]:
test = pd.read_csv(r'C:\Users\trodr\Documents\proyecto-torax-v2.0\01-dataset\mimic-cxr-2.1.0-test-set-labeled.csv')
test.columns

Index(['study_id', 'No Finding', 'Enlarged Cardiomediastinum', 'Cardiomegaly',
       'Lung Lesion', 'Airspace Opacity', 'Edema', 'Consolidation',
       'Pneumonia', 'Atelectasis', 'Pneumothorax', 'Pleural Effusion',
       'Pleural Other', 'Fracture', 'Support Devices'],
      dtype='str')

In [15]:
test.head(6)

,study_id,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Lesion,Airspace Opacity,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,58085167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,57798090,NaN,1.0,1.0,NaN,NaN,0.0,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN
2,50020371,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,52225063,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
4,59039129,NaN,NaN,1.0,NaN,1.0,-1.0,-1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN
5,55775366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
path = pd.read_csv(r'C:\Users\trodr\Documents\proyecto-torax-v2.0\0-descargas\SHA256SUMS.csv',delimiter=';')
path.columns

Index(['dicom_id', 'path'], dtype='str')

In [7]:
path.head(4)

,dicom_id,path
0,a688ad339cb18a877f53dea5d900186ac50170507ad72e...,IMAGE_FILENAMES
1,26794be6ea7916cd4b4017b45b9c34c3c31f645a03a9cd...,LICENSE.txt
2,af51555bca6c6caa60ac75759ad9f022cf86a7ce8e24c9...,README
3,3f721831529e9604c99e3bd999483321e0e0648c598735...,files/p10/p10000032/s50414267/02aa804e-bde0afd...

In [ ]:
union
path
test
path.merge(df2, left_on='lkey', right_on='rkey')

In [11]:
df = path.merge(union, left_on='dicom_id', right_on='dicom_id')
df.head(6)

Empty DataFrame
Columns: [dicom_id, path, subject_id, study_id]
Index: []

In [24]:
# Filtrar filas donde dicom_id sea ese valor
union[union['dicom_id'] == '174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962']

                                       dicom_id  subject_id  study_id
1  174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962    10000032  50414267

In [20]:
pd.set_option('display.max_colwidth', None)
path.head(6)

,dicom_id,path
0,a688ad339cb18a877f53dea5d900186ac50170507ad72e416a2fd88a63e8d321,IMAGE_FILENAMES
1,26794be6ea7916cd4b4017b45b9c34c3c31f645a03a9cd6c591c529b92435042,LICENSE.txt
2,af51555bca6c6caa60ac75759ad9f022cf86a7ce8e24c9bdb3fe497e159795fb,README
3,3f721831529e9604c99e3bd999483321e0e0648c5987351570fe45e48c190948,files/p10/p10000032/s50414267/02aa804e-bde0afdd-112c0b34-7bc16630-4e384014.jpg
4,dc00f099dadf5c38ead73ad9e768cee82b893402d02d588ebdca55f26f6db117,files/p10/p10000032/s50414267/174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962.jpg
5,43d1a78a3583971d8a1159e7769db9bda27625dec8c14b6731ef87245919cce3,files/p10/p10000032/s53189527/2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab.jpg

In [22]:
union.head(6)

                                       dicom_id  subject_id  study_id
0  02aa804e-bde0afdd-112c0b34-7bc16630-4e384014    10000032  50414267
1  174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962    10000032  50414267
2  2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab    10000032  53189527
3  e084de3b-be89b11e-20fe3f9f-9c8d8dfe-4cfd202c    10000032  53189527
4  68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714    10000032  53911762
5  fffabebf-74fd3a1f-673b6b41-96ec0ac9-2ab69818    10000032  53911762

In [27]:
import pandas as pd

# Cargar archivos
labels   = pd.read_csv(r"C:\Users\trodr\Documents\proyecto-torax-v2.0\01-dataset\mimic-cxr-2.1.0-test-set-labeled.csv")
metadata = pd.read_csv(r"C:\Users\trodr\Documents\proyecto-torax-v2.0\01-dataset\mimic-cxr-2.0.0-metadata.csv")

# union: dicom_id, subject_id, study_id (ya lo tenías)
union = metadata[['dicom_id', 'subject_id', 'study_id']].copy()

# Merge labels (solo tienen study_id) con union (que tiene dicom_id)
df = union.merge(labels, on='study_id', how='inner')

# Construir full_path
BASE_DIR = r"C:\Users\trodr\Documents\proyecto-torax\01-dataset\archive\official_data_iccv_final"
p_prefix = union['subject_id'].astype(str).str[:2]

df['full_path'] = (
    BASE_DIR + "\\files"
    + "\\p" + df['subject_id'].astype(str).str[:2]
    + "\\p" + df['subject_id'].astype(str)
    + "\\s" + df['study_id'].astype(str)
    + "\\" + df['dicom_id'].astype(str) + ".jpg"
)

print(df.shape)
print(df[['dicom_id', 'subject_id', 'study_id', 'full_path']].head())

(1029, 18)
                                       dicom_id  subject_id  study_id  \
0  687754ce-7420bfd3-0a19911f-a27a3916-9019cd53    10032725  50331901
1  fd4126e5-c5485b35-3bbc48fc-acb448fa-fb1b42b7    10032725  55504914
2  e2856783-ffa5ec26-043b0303-21aeddc6-b11b2876    10046166  57977208
3  7f6d7289-9941e757-2663be13-0dde50f8-5d2670aa    10183775  52835225
4  e35d7c70-3f278882-4f133ee9-184f4d7e-fa32a4d7    10268877  53452091

                                                                                                                                                            full_path
0  C:\Users\trodr\Documents\proyecto-torax\01-dataset\archive\official_data_iccv_final\files\p10\p10032725\s50331901\687754ce-7420bfd3-0a19911f-a27a3916-9019cd53.jpg
1  C:\Users\trodr\Documents\proyecto-torax\01-dataset\archive\official_data_iccv_final\files\p10\p10032725\s55504914\fd4126e5-c5485b35-3bbc48fc-acb448fa-fb1b42b7.jpg
2  C:\Users\trodr\Documents\proyecto-torax\01-dataset\archive\official_data_iccv_final\files\p10\p10046166\s57977208\e2856783-ffa5ec26-043b0303-21aeddc6-b11b2876.jpg
3  C:\Users\trodr\Documents\proyecto-torax\01-dataset\archive\official_data_iccv_final\files\p10\p10183775\s52835225\7f6d7289-9941e757-2663be13-0dde50f8-5d2670aa.jpg
4  C:\Users\trodr\Documents\proyecto-torax\01-dataset\archive\official_data_iccv_final\files\p10\p10268877\s53452091\e35d7c70-3f278882-4f133ee9-184f4d7e-fa32a4d7.jpg

In [28]:
df.columns

Index(['dicom_id', 'subject_id', 'study_id', 'No Finding',
       'Enlarged Cardiomediastinum', 'Cardiomegaly', 'Lung Lesion',
       'Airspace Opacity', 'Edema', 'Consolidation', 'Pneumonia',
       'Atelectasis', 'Pneumothorax', 'Pleural Effusion', 'Pleural Other',
       'Fracture', 'Support Devices', 'full_path'],
      dtype='str')